### PR TITLE
Replace with Lock Mechanism accessory which seems more suitable, add nodemon for testing.

### PR DESCRIPTION
**Pull request by dwaan**
1. I replace Switch accessory with Lock Mechanism accessory.
2. Hide error log when plugin can't connect to AdGuard Home server for example because of the server disconnected from network.
3. Introduce JAMMED status when plugins can't reach AdGuard Home server.

Side node: The new code need to be more more optimized which I'm currently working now.

### CODE REVIEW

**Comment by dotWee** [comment]
+1 for this pr! 

Installed the npm package a few weeks ago from your branch and it's been working flawlessly, totally forgot about it. 
Thanks for sharing your code!

@dwaan please check this out!

**Comment by davidmerrique** [comment]
@dwaan Thanks! 
Are you interested in taking over this plugin? 
I don't use Homebridge anymore, so I won't be updating it.

**Comment by dwaan** [comment]
@davidmerrique Sure, I would gladly help maintaining this plugins.

**Comment by dwaan** [comment]
Hey @davidmerrique, I have a problem publishing the plugin to npm. Currently I don't have permission to publish it using the same name. Do you mind to give permission to my npm account? My account is : dwaan

**Pull request merged**
